version: 3
images:
  base_image: 
    name: 'quay.io/ansible/ansible-runner:latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
additional_build_steps:
  # prepend_base:
  #   - RUN echo "Additional steps for prepend_base"
  append_base: None
  
